# Generated by Django 5.0.1 on 2024-02-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0002_photograph_category_photograph_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photograph",
            name="category",
            field=models.CharField(
                choices=[
                    ("NEBULOSA", "Nebulosa"),
                    ("ESTRELA", "Estrela"),
                    ("GALAXIA", "Galaxia"),
                    ("PLANETA", "Planeta"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
