# Generated by Django 5.0.1 on 2024-02-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0003_alter_photograph_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
