# Generated by Django 5.0.1 on 2024-02-14 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0006_photograph_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="photograph_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
