# Generated by Django 5.0.1 on 2024-02-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photograph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("legend", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("file_name", models.CharField(max_length=100)),
            ],
        ),
    ]
