# Generated by Django 5.0.1 on 2024-02-09 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="category",
            field=models.CharField(
                choices=[
                    ("NEBULOSA", "Nebuloso"),
                    ("ESTRELA", "Estrela"),
                    ("GALAXIA", "Galaxia"),
                    ("PLANETA", "Planeta"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="photograph",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="photograph",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
