# Generated by Django 5.0.1 on 2024-02-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0004_photograph_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photograph",
            name="file_name",
        ),
        migrations.AddField(
            model_name="photograph",
            name="file",
            field=models.ImageField(blank=True, upload_to="photographs/%Y/%m/%d/"),
        ),
    ]
